create table if not exists public.swimming_mode_history (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  scheduled_end_at timestamptz not null,
  ended_at timestamptz,
  source text not null check (source in ('manual', 'automatic')),
  created_at timestamptz not null default now(),
  constraint swimming_mode_history_dates_check
    check (scheduled_end_at >= started_at and (ended_at is null or ended_at >= started_at))
);

create index if not exists swimming_mode_history_started_at_idx
  on public.swimming_mode_history (started_at desc);

alter table public.swimming_mode_history enable row level security;

drop policy if exists "Anyone can read swimming mode history"
  on public.swimming_mode_history;

create policy "Anyone can read swimming mode history"
  on public.swimming_mode_history
  for select
  to anon, authenticated
  using (true);

grant select on public.swimming_mode_history to anon, authenticated;

create or replace function public.track_swimming_mode_history()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := now();
  v_old_active boolean := old.swimming_mode_until is not null
    and old.swimming_mode_until > v_now;
  v_new_active boolean := new.swimming_mode_until is not null
    and new.swimming_mode_until > v_now;
begin
  if not v_old_active and v_new_active then
    insert into public.swimming_mode_history (
      started_at,
      scheduled_end_at,
      source
    ) values (
      v_now,
      new.swimming_mode_until,
      case
        when new.swimming_mode_source = 'automatic' then 'automatic'
        else 'manual'
      end
    );
  elsif v_old_active and not v_new_active then
    update public.swimming_mode_history
    set ended_at = v_now
    where id = (
      select history.id
      from public.swimming_mode_history history
      where history.ended_at is null
      order by history.started_at desc
      limit 1
    );
  elsif v_old_active and v_new_active
    and (
      new.swimming_mode_until is distinct from old.swimming_mode_until
      or new.swimming_mode_source is distinct from old.swimming_mode_source
    ) then
    update public.swimming_mode_history
    set
      scheduled_end_at = new.swimming_mode_until,
      source = case
        when new.swimming_mode_source = 'automatic' then 'automatic'
        else 'manual'
      end
    where id = (
      select history.id
      from public.swimming_mode_history history
      where history.ended_at is null
      order by history.started_at desc
      limit 1
    );
  end if;

  return new;
end;
$$;

drop trigger if exists track_swimming_mode_history_trigger
  on public.pool_control;

create trigger track_swimming_mode_history_trigger
after update of swimming_mode_until, swimming_mode_source
on public.pool_control
for each row
execute function public.track_swimming_mode_history();

insert into public.swimming_mode_history (
  started_at,
  scheduled_end_at,
  source
)
select
  now(),
  control.swimming_mode_until,
  case
    when control.swimming_mode_source = 'automatic' then 'automatic'
    else 'manual'
  end
from public.pool_control control
where control.id = 1
  and control.swimming_mode_until > now()
  and not exists (
    select 1
    from public.swimming_mode_history history
    where history.ended_at is null
      and history.scheduled_end_at > now()
  );

create or replace function public.get_sensor_error_history(
  p_range text default '24h'
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := now();
  v_start timestamptz;
  v_total bigint := 0;
  v_periods jsonb := '[]'::jsonb;
begin
  case lower(p_range)
    when '24h' then v_start := v_now - interval '24 hours';
    when '7d' then v_start := v_now - interval '7 days';
    when '30d' then v_start := v_now - interval '30 days';
    else
      raise exception 'Unsupported statistics range: %', p_range
        using errcode = '22023';
  end case;

  with previous_reading as (
    select upper(ps.status) as status, ps.created_at
    from public.pool_status ps
    where ps.created_at < v_start
      and ps.device_online is true
    order by ps.created_at desc
    limit 1
  ),
  range_readings as (
    select upper(ps.status) as status, ps.created_at
    from public.pool_status ps
    where ps.created_at >= v_start
      and ps.created_at <= v_now
      and ps.device_online is true
  ),
  sequenced as (
    select
      readings.status,
      readings.created_at,
      lag(readings.status) over (order by readings.created_at) as previous_status
    from (
      select * from previous_reading
      union all
      select * from range_readings
    ) readings
  ),
  starts as (
    select s.created_at as started_at
    from sequenced s
    where s.created_at >= v_start
      and s.status = 'ERROR'
      and s.previous_status is distinct from 'ERROR'

    union all

    select v_start
    where exists (
      select 1 from previous_reading previous
      where previous.status = 'ERROR'
    )
  ),
  periods as (
    select
      starts.started_at,
      (
        select min(reading.created_at)
        from range_readings reading
        where reading.created_at > starts.started_at
          and reading.status <> 'ERROR'
      ) as ended_at
    from starts
  ),
  numbered as (
    select
      periods.*,
      count(*) over () as total_periods,
      row_number() over (order by periods.started_at desc) as newest_first
    from periods
  )
  select
    coalesce(max(numbered.total_periods), 0),
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'started_at', numbered.started_at,
          'ended_at', numbered.ended_at,
          'active', numbered.ended_at is null,
          'duration_seconds', greatest(
            0,
            extract(epoch from (coalesce(numbered.ended_at, v_now) - numbered.started_at))::bigint
          )
        )
        order by numbered.started_at
      ) filter (where numbered.newest_first <= 100),
      '[]'::jsonb
    )
    into v_total, v_periods
  from numbered;

  return jsonb_build_object(
    'total_periods', v_total,
    'periods', v_periods
  );
end;
$$;

create or replace function public.get_swimming_mode_history(
  p_range text default '24h'
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := now();
  v_start timestamptz;
  v_total bigint := 0;
  v_sessions jsonb := '[]'::jsonb;
begin
  case lower(p_range)
    when '24h' then v_start := v_now - interval '24 hours';
    when '7d' then v_start := v_now - interval '7 days';
    when '30d' then v_start := v_now - interval '30 days';
    else
      raise exception 'Unsupported statistics range: %', p_range
        using errcode = '22023';
  end case;

  with sessions as (
    select
      history.started_at,
      coalesce(history.ended_at, history.scheduled_end_at) as ended_at,
      history.source,
      history.ended_at is null and history.scheduled_end_at > v_now as active
    from public.swimming_mode_history history
    where history.started_at <= v_now
      and coalesce(history.ended_at, history.scheduled_end_at) >= v_start
  ),
  numbered as (
    select
      sessions.*,
      count(*) over () as total_sessions,
      row_number() over (order by sessions.started_at desc) as newest_first
    from sessions
  )
  select
    coalesce(max(numbered.total_sessions), 0),
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'started_at', numbered.started_at,
          'ended_at', numbered.ended_at,
          'source', numbered.source,
          'active', numbered.active,
          'duration_seconds', greatest(
            0,
            extract(epoch from (least(numbered.ended_at, v_now) - numbered.started_at))::bigint
          )
        )
        order by numbered.started_at
      ) filter (where numbered.newest_first <= 100),
      '[]'::jsonb
    )
    into v_total, v_sessions
  from numbered;

  return jsonb_build_object(
    'total_sessions', v_total,
    'sessions', v_sessions
  );
end;
$$;

revoke all on function public.get_sensor_error_history(text) from public;
revoke all on function public.get_swimming_mode_history(text) from public;
grant execute on function public.get_sensor_error_history(text) to anon, authenticated;
grant execute on function public.get_swimming_mode_history(text) to anon, authenticated;
